import os
from dotenv import load_dotenv
load_dotenv()

#EMAIL HOST
EMAIL_HOST = os.getenv('EMAIL_HOST')

#EMAIL LOGIN - RECEIVING
EMAIL_USER_RECEIVING = os.getenv('EMAIL_USER_RECEIVING')
EMAIL_PASS_RECEIVING = os.getenv('EMAIL_PASS_RECEIVING')

#EMAIL LOGIN - RECEIVABLE
EMAIL_USER_RECEIVABLE = os.getenv('EMAIL_USER_RECEIVABLE')
EMAIL_PASS_RECEIVABLE = os.getenv('EMAIL_PASS_RECEIVABLE')